version: '3.7'

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    image: devnetwork-server
    container_name: devnetwork-node-server
    command: npm start
    volumes:
      - .:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file: ./.env
    environment:
      - NODE_ENV=development
    networks:
      - app-network
  mongo:
    image: mongo
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: devnetwork-client
    container_name: devnetwork-react-client
    command: npm start
    volumes:
      - ./client/:/usr/app
      - ./client/node_modules/:/usr/app/node_modules
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
    app-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local